import uuid
from service.RagasEvaluationService import RagasEvaluationService
from sql_app.database import DbDepends
import ast
import json
import re
import asyncio
import pytest
import pytest_asyncio
from service.chatapi_service import fetch_result
from langchain_openai import AzureChatOpenAI
from ragas import SingleTurnSample
from ragas.metrics import Faithfulness
from ragas.llms import LangchainLLMWrapper
from ragas.metrics import LLMContextPrecisionWithoutReference
from utils.opensearch_utils import OpenSearchUtils
from langchain_core.documents import Document
import csv
# Initialize OpenSearch
OpenSearchUtils.init()
AZURE_OPENAI_ENDPOINT = "https://oai-ceast-hally-sandbox.openai.azure.com/"
AZURE_OPENAI_API_KEY = "e52a924ffe3541189d3d46a24f0afb64"
AZURE_OPENAI_API_VERSION = "2024-06-01"
AZURE_OPENAI_DEPLOYMENT_ID = "gpt-4o"
# Initialize the LLM

llm = AzureChatOpenAI(
    openai_api_version=AZURE_OPENAI_API_VERSION,
    openai_api_key=AZURE_OPENAI_API_KEY,
    azure_endpoint=AZURE_OPENAI_ENDPOINT,
    deployment_name=AZURE_OPENAI_DEPLOYMENT_ID,
)

session_id = str(uuid.uuid4())
#scitex
# user_inputs = ['Feeder - C500 Gripper Child Parts',
#  'Technical Note - Serra Loose Screws Risk Torque Verification',
#  'OPV - Inspecting the Transport Belts Motor',
#  'Double-Side Printing - Best Practices',
#  'Replacing the Shaft of the OPV Transport Belts’ Motor',
#  'Print Engine - Print Head Return Process',
#  'Replacing the Brackets of the Lateral Squarer Extender on the Stacker',
#  'HP Customer Portal Guide Ver 2.0',
#  'Replacing the Tornado Impeller Motor',
#  'C550 Operator Training Level 2 Ver 1.3',
#  'Txx_C550 Operator Training Level 2 Ver 1.3 (Spanish)',
#  'Stacker - Transport Belts Movement Inspection',
#  'OPV - Flipping the Plate Roller',
#  'Aerosol - Cleaning the Clogged Manifolds',
#  'MI Controllers Troubleshooting',
#  'OPV Drivers and Inverter Mapping',
#  'Print Engine - Replacing the Web Wipe Cassette (WWC) Assembly',
#  'Installing the EtherCAT Cable for ACS on Train 0',
#  'C550 VP ATP-Integration Procedure',
#  'Cleaning the Analog Vacuum Pistons',
#  'Replacing Heater in Dryer IR Cassette',
#  'C500 Operator Training  MRR 11 SP2.5 Continuous Stacker Student book Ver 2.5',
#  'C500 Operator Training  MRR 11 SP2.5 Premium Stacker Student book Ver 2.4 (PL)'
# ]

user_inputs = ['CA394-05492']
# #indigo
# user_inputs = [
#  ' CA393-10920 because its the installation guide, smooth work guys. Tech notes tell me to get a document you dont have and isnt in CE suitcase',
#  ' The steps showing the front dripping fan installation and also the systab changes',
#  " It's not available in my software which is the latest available.",
#  ' How i the setup on Indigo for adding zero round without printing color',
#  ' document where and how to set your user/operator level setting. so this way you can find level 3 documentation ',
#  ' The steps to do on the hp 12000 or what  i need looking for ',
#  ' What to do if shutting down the Indigo 7900 long term',
#  ' 6900 Installation Manual',
#  ' which would be the most common test with this propierty',
#  ' a guide with description of this matter',
#  ' what to use for cleaning the rubber IFR roller',
#  ' A video how to replaced pip foil manually',
#  ' Silica filter replacement for 12" filter',
#  ' which nip is the "fr" nip, or a map of  what each of the nips are called, or something useful. ',
#  ' level 2  and 3 training ',
#  ' Informacion de configuracion y uso del papel ISBC@Rfid en Indigo 7900',
#  ' where to find within service center',
#  ' material safety data sheets',
#  ' I was looking for information on how to use the Adaptive Image Scaling jig.',
#  ' late color management',
#  ' a trouble shooting guide for this error',
#  ' color up document',
#  ' max print area on a HP7900',
#  ' HP Indigo Print Beat Guideline for commercial presses 4AA5-7533ENW, May 2016, Rev 6 , looking for the L&P version ',
#  ' Part Number: CA494-30930 Rev01_PRINT.pdf\n\nNOTE: Installation von HP Indigo ElectroInk Premium White an HP WS 20.000',
#  ' Overview of PARS with technical specifications.',
#  ' error Bitmap viewer - Cannot open image java.lang.NullpointerException',
#  ' HP Indigo ElectroInk Primer how to guide for the 7x00. I had the following filters: 7900 and English',
#  ' what to do when the ink dont stick',
#  'How to print Raised effects',
#  'IMO_FILTERS_REPLACE_CLEAN_FLOAT ',
#  "No - I'm looking for Automatic Alert Agent How-To-Guide\n",
#  "Waste bottle full sensor.\nThe press is telling me my waste bottle is full and it's not"
#  ]

# user_inputs = [
#  ' reverse printing with hp smartstream designer',
#  ' a troubleshooting guide for the 7xxx series stacker including symptoms and common fixes ',
#  ' 100K blanket change video ',
#  ' Something bout the issue. ',
#  ' use instruction of D9U80A',
#  ' how to change ebm  clamp\n',
#  ' What light is approved for color review.',
#  ' actual print size/ image size',
#  ' Some documention on the handheld meter that is provided for each of the 10 presses we just acquired. ',
#  ' Anything about slip sheets or something in the manual. There is nothing that states divider or default image in the manual that I found.',
#  ' Documents on how to properly perform the Image Placement Calibration',
#  ' 颜色校正',
#  ' A document on PIP refresh. Possibly a way to adjust how often the PIP refresh occurs. ',
#  ' changement moteur cleaning station',
#  ' complete process of how to build new ink from beginning to end.',
#  ' recycling sisitem series 4 ',
#  ' 100k Value pack upgrade, How to...',
#  ' rdu backwash procedure',
#  ' what it is, issues and solutions',
#  ' its for cleaning bid roller and replacing bid base',
#  ' CA495-09920',
#  ' PLC reset',
#  ' CA339-10210\n\nOnly document to explain brand protection',
#  ' Resources for troubleshooting a stock not feeding',
#  ' How to use refine color function on Indigo 7900',
#  ' ts steps',
#  ' What profile to use for what color management',
#  ' Show an error code  description.',
#  ' Troubleshooting',
#  ' how to handle thngs',
#  ' ho to change feeder drawer cable',
#  'match exact search. ',
#  ' Documents related to Press performance tuning',
#  ' Documents showing how to do it',
#  ' Video documentation',
#  ' passagem de substarte\n',
#  ' a doc or a video ',
#  ' diagram for the imaging oil route on HP 12000',
#  ' Recommended ink tank rebuild intervals for HP Indigo 12000',
#  ' spot color alias',
#  'Need video support on how to replace duplex belts on 5600/5500',
#  ' dokument with explanation of pip-encoder calibration, or video',
#  ' how to do it',
#  ' how to clean video',
#  ' Step by step instructions',
#  ' Training material and beginners guide to use PrintOS Box',
#  ' PRINTING IN  PE FOR COSMETIC SQEEZE TUBES',
#  ' YTD for quark 8 for download please',
#  ' why am I getting this error',
#  ' nothing ',
#  ' parts catalog ',
#  ' TS5ES-00031',
#  ' Information ',
#  ' how to manage metalized substrate',
#  ' CA393-11210',
#  ' Feed head removal and replacement ',
#  ' CA393-09640',
#  ' help',
#  ' an answer',
#  ' something helpful',
#  ' inks MSDS',
#  ' HOW AND WHERE THE CVC TEMP SENSOR IS LOCATED',
#  ' a video of the of the spm movement engage and disengage',
#  ' CA394-08040',
#  ' CA339-10210\n\nThis is the ONLY document that describes Code 1 and Code 2 of Brand Protection',
#  ' how to place spot mark\n',
#  ' Information on color beat coins',
#  ' The document CA393-06450 , when i search for that the knowledge zone tells me it doesnt exist',
#  ' Régler travers recto/verso',
#  ' Dynamic Prism',
#  ' TN-2658',
#  ' no info on this \n',
#  ' CA394-25251',
#  ' CA393-16614',
#  ' S5ES-00035',
#  ' DLC unit',
#  ' T2 Calibrations how and when',
#  ' Video or instruction showing how to remove finger belt motor, belts, and pulleys from the feeder bridge of 1x000 presses',
#  ' jump over seam calibration',
#  ' PrintOS pdf',
#  ' instructions on how to set this',
#  ' omp',
#  ' SETTING PARS',
#  ' warning #894283',
#  ' CA339-10210 - SW v15.2 CE Training.pdf\n\nThis is the only document that explains the Brand Protection Code 1 and Code 2',
#  ' There is no new version of cat p 7000 file available.',
#  ' a course',
#  ' reprime seperator',
#  ' TN-2658 - Release of Press Software v16.2 and I-Fix 3 Installation.pdf',
#  ' A vídeo explaning how to replace the balance roller for S4',
#  ' shelf life of seried 3 ink',
#  ' instructions on fixing the problem. ',
#  ' hp indigo ws6xxxx level 1 operator guide',
#  ' How to return a used bid base',
#  ' measuring ruller',
#  ' customer document  on the ink',
#  ' CA493-05520',
#  ' a listing of lifespan',
#  ' Something showing how to disassemble  the unit and replace the roller',
#  ' Anything to show me how to replace a charge roller',
#  ' A demonstration on how to properly calibrate density for my inks.',
#  ' v12 Replacing ink tubes when empty',
#  ' SAFETY DATA SHEET OF THE IMAGINE OIL AND TECHNICAL DATA SHEET',
#  ' CA339-10210 - SW v15.2 CE Training.pdf',
#  ' c',
#  ' More information for help on this issue.',
#  ' the white paper\nHP Indigo for Food Packaging Printing Regulatory Overview (4AA4-8153ENW, February 2015).',
#  ' manifold system and water system diagrams',
#  ' how to raise it',
#  '  ',
#  ' a video on the lifespan and replacement of the filter itself',
#  ' A list of all approved substrates',
#  ' HP SmartStream Designer for Adobe InDesign CC2024',
#  ' How can we clear them out without adding to our inventory',
#  ' Smart Stream Designer 19 for InDesign 24',
#  ' electrometer board calibration wizard',
#  ' the service manual',
#  ' emergency oem errors',
#  ' idem',
#  ' Step by step instructions on how to Clean (not replace)',
#  ' double hit ink',
#  ' ink flow adjustment',
#  ' Video showing or Documentation explaining how to remove and replace this worn shaft on Exit conveyor  in Indigo 5900 Press.',
#  ' datasheet\n',
#  ' BID',
#  ' part number',
#  ' instruction how to install and use silver ink. Tips',
#  ' Technical info ',
#  ' Viedeo mit beschreibung',
#  ' Replace Feeder Belt HTD 5MM Pitch 450 Teeth',
#  " Hello,\nI'm searching to know how to use the transparent ink.",
#  ' AUTO BIAS',
#  ' a video that walks me through the steps to replace the motor. Instead there is a video that has nothing to do with my machine',
#  ' la liste des differents primeurs',
#  ' how to return a bid or a dev. roller',
#  ' information on how to solve ink development problem',
#  ' a link describing or a link to take me to a FAQ page',
#  ' maximum total ink load as a percentage',
#  ' v electrode',
#  ' How to guide with steps including screenshots on how to connect a new press to PrintOS',
#  ' error',
#  ' the answer',
#  ' Une vidéo explicative du changement de la sous-couche sur serie 4',
#  'hard scratch on image',
#  ' A statement regarding HP ElectroInk compliance to EC regulation 1223/2009',
#  ' ADJUSTMENT THROUGH PAPER',
#  ' please i won t a procedure exact for change the color orange to silver and silver to orange. thanks.',
#  ' ink tank is not resetting on the cyan',
#  ' how to fix it ',
#  ' information about how to use technical inks in the L&P DFE',
#  ' drawer 2 keeps on skewing',
#  ' differents primeurs',
#  ' Usage guidelines for charge roller',
#  ' Checklist to check what is causing this problem',
#  ' Fichas dados de segurança',
#  ' Video on how to replace impeller',
#  ' ...',
#  ' fiters changer',
#  ' ink can storage best practices',
#  ' a video',
#  'ghlkjh',
#  ' stop eanble automatic calibration\n',
#  ' Error: explanation what can do ',
#  ' Replacing Stacker bride belts',
#  ' ink pump replacement for HP 6900',
#  ' Drawer 1 feeder',
#  ' lifespam',
#  ' Print area specs for duplex for the 12K',
#  ' Ways to increase ink density',
#  ' pip underlayer replacement',
#  ' 6k 3d footprint for site prep',
#  ' french',
#  ' the damn parts catalog!',
#  ' how to drain the tank',
#  ' video on fixes ',
#  ' CA393-04290',
#  ' Stacker timing belt\n',
#  ' How to set up an imposition  in relation to the diecutter',
#  ' how to delete a markset and what it is connected to',
#  ' parts catalog',
#  ' help finding on how to clean out the floor waste tank.   ',
#  ' All ink file for the machine I chose',
#  ' Potentiometer',
#  'CT345-29910 ich finde kein Video ',
#  ' Daily, Weekly, and Monthly maintenance chaecklist for HP indigo 100k',
#  ' 7k parts manual',
#  ' front and back registration',
#  " Where to find the transfer screen. The press is telling me to goto the transfer screen, but don't know where that is",
#  ' ILP',
#  ' reinsertion',
#  ' tutorial',
#  ' i was hoping to find information about the cushion fan......... ',
#  ' minimum point size of text',
#  ' Indigo WS25K',
#  ' maintenance',
#  ' Document or video explaining it or at very least a part number to help me locate a new belt',
#  ' how to drain water/oil seperator on 12k press',
#  ' Press performance tuning for 12000 press.',
#  ' CA592-00250 ',
#  ' informacion docmumentos videos',
#  ' how to adjust blanket temp',
#  ' CA393-05250',
#  ' pip underlay change',
#  ' documentation explaining how to use the tool that comes with the DFE',
#  ' the installer for for illustrator 27.0 ',
#  ' how to get new activation code for smartstream for InDesign 2023',
#  ' manual,TN',
#  ' for a document that shows what the minimum and maximum specs are for substrates for the 30k',
#  ' Make page 2 Grayscale, or make all Even Pages Grayscale.',
#  ' What I need to order to print with metallic ink ',
#  ' automatic color adjust',
#  ' https: Information on Print Beat for PWP Presses - Data dictionary info etc.\n\n',
#  ' Other options other than automatic alignment on press',
#  ' Impression Ventilation Pressure Switch',
#  ' speed of machine',
#  ' how to control imaging oil over flow\n',
#  ' calibration cans',
#  ' BarCode Studio for MacOS',
#  ' Barcode Studio for MacOS download',
#  ' Was looking for information on issues with the air hose. Excessive air currently coming from our hose.',
#  ' itc heater pump',
#  ' How to replace the silica gel filter',
#  ' It only show the version for PC',
#  ' how to add a slip sheet',
#  ' nothing',
#  ' Where it is on the DFE or where we put templates so we can generate VD jobs by dropping csvs in the hotfolder',
#  ' Looking for instruction on how to prepare files using silver ink',
#  ' des reponses et ou chercher',
#  ' if print VDP file, press start hang',
#  ' buckle adjustment',
#  ' Steps to add the colors and set up the ticket template',
#  ' user manual in English for HP PrintOS Production Pro for Commercial 8.0.1.122.0',
#  " I'd like to know if it's possible to add text, a Tab and then more text",
#  ' list',
#  '  video changement underlayer',
#  ' How to setup GS1 data matrix',
#  ' sw doc',
#  ' a video or pdf',
#  ' something to help me resolve this issue ',
#  ' how to add my operators to print os',
#  ' Onscreen display / screen grabs of where this adjustment can be made\n',
#  ' font converter',
#  ' PUW AND RW SERVICE',
#  ' https: how to replace the stacker vacuum box.',
#  ' 6800 Press.',
#  ' Draining Excess Imaging Oil from Reservoir',
#  'I could not find Reflex Blue Ink Definition',
#  ' PARS adjustment, functionality movie, PARS troubleshooting',
#  ' video',
#  ' kit bobbin wire ',
#  ' a guide ',
#  ' hhh',
#  ' CT345-60870 heat exchanger with copper fitting',
#  ' troubleshooting',
#  ' A place to buy Smartstream Designer',
#  ' DESMONTAR CORREA',
#  ' chargeroller kohle wechseln\n',
#  ' Mech Init Time Out. State. STATE_INCHING_MECH1',
#  ' rio',
#  ' info on how to use 12k parts amnual',
#  ' how to replace the water heater in the ink cabinet',
#  ' 828894',
#  ' Level 2 training class\n',
#  ' a process for obtaining a .PDF file for a job that we need to archive',
#  ' impression brake',
#  ' video changement sous couche',
#  ' a description of what blanket ironing is ',
#  ' L3 Training content',
#  ' Calculator to see how much PMS clicks we use daily.',
#  ' Steps to resolve issues via troubleshooting',
#  'TÜV Austria  über Kompostierbarkeit',
#  'nasljxl',
#  ' Un document sur la résistance des encres ElectroInk aux Rayons UV',
#  ' Fiche technique pour imaging oil comment recycler',
#  ' I expect to fine the 7900 parts htm. ',
#  ' video for anti-soap maintenance',
#  ' Help',
#  ' a description on how to subscribe to such report to check if operators have ticked the maintenance activities',
#  ' TS4ES-00024',
#  ' Well, the document I stated. I just found a TN with the link to the file but the links are not working.',
#  'dprymula@epacflexibles.com\n',
#  ' max diameter roll at UW',
#  ' The list of approved update to apply to our Indigo presses',
#  ' documents of were it is',
#  ' Feeder 24 voltage warning',
#  ' how to create more color strategies with different ink sets',
#  ' troubleshooting doc',
#  ' how to activate reduce waste option',
#  ' flushing procedure etc',
#  ' HP_GRACoL_HVYGCR_REL_DL.icc and instructions to install',
#  ' Calibrating the Waste Bottle Sensors',
#  ' PDF file containing all required product safety data information',
#  ' n',
#  ' documentation, video...',
#  ' gripper shaft replace gripper pads mp4',
#  ' how to replace CA397-01970 SP,FEEDER BRIDGE VACUUM BELT(5X) (video, docs...)',
#  ' cleaning the writing head procedure',
#  ' imp drum troubleshooting\n',
#  ' 100k Speed table how fast it runs with using less colors\n',
#  ' trouble shooting ink temp',
#  ' color calibration continous',
#  ' video of where lubrication point is',
#  ' Pack and Submit for variable data',
#  ' help with part number and replace',
#  ' in the search bar',
#  ' HOW TO REPLACE ,DRIVE  SHAFT ASSY ON DEPOSITING MODULE',
#  ' How to get someone off of the list for receiving Print Beat emails?',
#  ' résolution probleme temperature presse',
#  ' why i have white ink spots showing up',
#  ' a video on how to become a 5000 operator',
#  ' A guide to replacing drawer motor',
#  ' how to replace pip encoder (optical rotary)',
#  ' ink file',
#  ' Proximity Sensor',
#  ' trouble shooting color difference from leading edge to end of frame',
#  ' video',
#  ' TS5ES-00015',
#  ' Bright solid foil',
#  ' servicing the web handling system ',
#  ' how to take the test for level 1 operator',
#  '  CA394-00760 On-press Fast Ink Replacement',
#  ' ink development problem',
#  ' How to replace tray side blower cables',
#  ' 7900 press parts catalog',
#  ' how to set bcs',
#  ' White ink installation manual',
#  ' Ort & platzierung der ITC  Pumpe und die dazu gehörigen Ventile , Fehlermeldung sagt das diese überprüft werden sollen .',
#  ' need the 7k parts htm  ',
#  ' A guide to how to change the shift times in PrintOS',
#  ' depositing belt vacuum',
#  ' specifiche del calcolo dei click di stampa',
#  ' HP Indigo visual color glossary - referred to in Indigo Spot Master 25K and 35K advanced Training',
#  ' vida util pips, blankets y bid',
#  ' HP INDIGO DIIGITAL PRESS SUPPLIES USAGE GUIDELINESS WORLDWIDE\n',
#  ' PAUTAS DE VIDA UTIL POR PRENSA',
#  ' LIFESPAM GUIDELINES',
#  ' LIFESPAM GUIDELINES',
#  ' wie man die pip bremse wechselt',
#  ' video or document',
#  ' ink calculator',
#  ' fiches de sécurité des encres pour WS6000 series',
#  ' Cleaning station in place sensor replacement',
#  ' a how to guide but I am seeing results for BID particle removal... seriously.',
#  ' Latest software I can upgrade to',
#  ' All the documents pertaining the MSDS for the supplies',
#  ' Document regarding this for A) Part number, and B) Secondary document detailing change/revision of style of physical component. ',
#  ' how to ',
#  ' ink tube placement in the ink station',
#  ' A VIDEO TO GO THROUGH PROCEDURE',
#  ' Water/oil recycle system maintenance.',
#  ' A method to convert PPML files to PDF',
#  ' electrometer error',
#  ' video',
#  ' how to adjust sensors for primer catch tray',
#  ' step by step process to load color on dfe\n',
#  " failure of bridge transporting motor 1 (80)  got this error while printing press doesn't want to printing at the moment due to this error.",
#  ' A VIDEO TO REPLACE A PART',
#  ' carbon brush and slip ring maintenance',
#  ' Instructions how to perform this',
#  ' how to clean te tank',
#  ' how to ',
#  ' not sure what it is',
#  ' I was looking for additional documentation on how to use adaptive halftoning and what situations to use it in. ',
#  ' the bcs area and how to inspect it',
#  ' gripper pads',
#  ' how to fix this error',
#  ' install video',
#  ' What is a VAT NO.?',
#  ' How to reset The MIC board',
#  ' The reason for white Ink leakage.',
#  ' PRIMING SYSTEM WASHING WIZARD',
#  ' video of replacing bid base and the callibrations to run',
#  ' specs on ink',
#  ' Pip Underlayer for the 7k',
#  ' general service routine by engineer',
#  ' bh',
#  ' An estimate on the percentage of waste material for a very high color accuracy level.',
#  ' FORMAT IMPRESSION  MAXIMUM',
#  ' a pdf with parts catalog ',
#  ' amitol heater replacement',
#  ' HP approved substrates.',
#  ' My current Maintenance contract including terms and information i.e information on the monthly or annual charges and maintenance contract terms ',
#  ' frequent pc clock modification error',
#  ' Conformity of HP Indigo ElectroInk with European Food Legislation\n\nInks: I only found old Certificate since 2018',
#  ' Sicherheitsdatenblätter Indigo 20000 + Indigo ws4500',
#  ' I may not be using the right search terms. ',
#  ' How to fill the Imaging Agent reservoir',
#  ' IFR Sensors',
#  " What IO(new and recycled) can be used between presses. Found info in Supplies Best Practice's Guide. Should be easier to find. ",
#  ' data sheet inks Y8M49A ',
#  ' A detailed description as to how to adjust the air puffs in the stacker',
#  ' Information to replace my parts. Search is useless garbage.',
#  ' Australia SmartStream designer license for Adobe InDesign 2022 for PC ',
#  ' IMAGE PLACEMENT',
#  ' Reference document showing which ITSBs are compatible with which inks.',
#  ' version of ink definition file used\n',
#  ' hoping to maintain counter for frequently reinstalled blankets',
#  ' indigo Site condition out of spec',
#  ' video del procedimiento',
#  ' Best practices of how to clean and refill recycling system',
#  ' TN-2541',
#  ' variable image in Smartstream Indesign',
#  ' The most recent font converter app',
#  ' CA493-03530',
#  ' CA493-03530',
#  ' The SDS',
#  ' document guidelines',
#  ' msds for all consumables',
#  ' tcp socket explain',
#  ' MP4',
#  ' site preparation guide 12000HD',
#  ' PrintOS how-to videos .. MOP assy .. BDU module.\n\n\nI need to watch video for this thing.',
#  ' TDS for imaging OIL, UN#',
#  ' a video',
#  ' Parts catalog for HP7900',
#  ' info about Easy release ink',
#  ' how to calibrate the electrometer',
#  ' How to view all the templates I have created. It appears they do not all show like there is some limit to how many I can view.',
#  'Is there a catalog for  the 5900?',
#  ' Parts catalog for HP Indigo 5900 Press',
#  ' Training guide / Video',
#  ' 100K preventive maintenance',
#  ' The msds sheets for the materials that CANT be returned via the HP Takeback Programme',
#  ' nothing\n',
#  " To define the metric's that the Print Beat reports are showing, wanted to find the definition of 'sheet'",
#  ' nothing',
#  ' Video zu finden ',
#  ' A sheet containing color density for measurements.',
#  " you can use 'this paper' instead of gloss paper\n",
#  ' lightfastness test for Orange ink',
#  ' data sheet/fact sheet about ink',
#  ' comment passer le papier\n',
#  ' partcatalog 7800',
#  ' video',
#  ' an answer',
#  ' CA394-05492',
#  ' wrinkles',
#  ' pip bearing',
#  ' excel spread sheets ',
#  ' !',
#  ' I need to know what and where it is',
#  ' General electroink info.',
#  ' MAINTENANCE PROCEDURES',
#  ' I wrote what i expected',
#  ' Barcode Studio 16.2 by TEC_IT for Mac',
#  ' pc power supply',
#  ' Some documentation describing what it is.',
#  ' 7900 parts catalog',
#  ' Troubleshooting for PCN_PERFECTOR_CONTROL_ERROR ',
#  ' Datasheet on how to use the easy release ink',
#  ' Guida alla sostituzione della cartuccia GLS Oil Pump ',
#  ' win 10 update 7900',
#  "Trying to find Safety Data Sheets for various HP indigo products in my shop.  The link to SDS's does not work!",
#  ' GESTION AUTOMATICA DEL STOCK.\nNECESITO UN MANUAL O ALGUIEN QUE ME AYUDE.',
#  ' HP Logo in vector format in order to use it for creating our promotional materials ',
#  ' calibration',
#  ' exactly what im searching for',
#  ' RESETING THE DRAWER LEVEL BUTTONS',
#  ' video how to do it',
#  ' Thick impression paper ',
#  ' How to guide',
#  ' HP 7k, ink safety data sheet, can please send PDF with safety data sheet for inks for 7K? Mail: psz@graphicwest.dk',
#  ' A video or document describing how to change the internal ITM Lamps',
#  ' Part number of the double BID Stand base, not the low high one',
#  ' the way to put it right',
#  ' how to do that',
#  ' SmartStream Designer for InDesign 2022\nVersion 17.x',
#  ' What to comment out to bypass these',
#  ' last video of how to do ',
#  ' Ruler order',
#  ' SmartStream indesign 2022',
#  ' how to calibrate or clean ',
#  ' Document Connectivity Configuration',
#  ' Silver ink storage',
#  " et j'ai réussi a le perdre.",
#  'manual usuario 6800\n',
#  ' transparent ink',
#  ' image skew wizard',
#  ' PLC main drive',
#  ' Something that explained when you need two bumps then when you need more than two and to use ink order',
#  ' video di ricambio della tanica',
#  ' not sure where to find it',
#  ' CABLE ASSY W18 MCN - ITM FUSE & ITM AIR',
#  ' CATP  HP Indigo 6P file',
#  ' manual for insetting',
#  ' Charge roller motor',
#  ' Reset',
#  ' Changelog, new things in the update',
#  ' PRB0041388',
#  ' P.Pro LnP v8.0, user guide for included Composer 6.0.',
#  ' exe file',
#  ' OPERATION GUIDE',
#  ' booklet or peal and reveal labels',
#  ' Something about CMYK value processing. All I found was something about t-shirts',
#  ' Trying to find and up to date version ',
#  ' S4 Color Change \n\nlike the How to rebuild ink.mp4 | CA494-12850  ,but than the "Color change" Wizard',
#  ' Feeder type C',
#  ' una guia de como limpiar la tesela',
#  ' ink calculator\n',
#  ' Lifespan supplies',
#  ' Something',
#  ' impression de filigrane commun',
#  ' CE training press software v16.3\nCE training press software v16.2',
#  ' press stop printing after this error pop up.',
#  ' SUPPLIES',
#  ' peu roller replacement',
#  ' the parts catalog for the 6K',
#  'meaning of green,orange and red lamp',
#  ' there is nothing here ',
#  ' anything to do with the software of the press, this site is completely useless',
#  ' something but found nothing about it',
#  ' a description howto install this s.note!',
#  ' Min. substrate size, and Min. image size',
#  ' Learn about lut',
#  ' 100k ods sensor',
#  ' CA393-04480',
#  ' A video that can tell me how to implement it, or an email with steps',
#  ' help',
#  ' Courses I can sign up for and travel to an HP campus for training',
#  ' Video or instructions',
#  ' How to giude for transparent, Rhodamin red, light yellow and reflex blue.',
#  ' a guide to green tag use',
#  ' ilp dryer heater k1 ',
#  ' comment insérer un noir 30% entre 2 blancs pour vitrophanie',
#  ' root cause of this ',
#  ' Skew test\n',
#  ' smartstream for indesign 17',
#  ' HOW TO REPLACE IT',
#  ' Part catalog ws6x00',
#  ' how to change out brush roller in the ILP',
#  ' how to change mark sets in production pro to inches, my user profile is using inches but marks are still in mm.',
#  ' La référence de la graisse nsk pour les ibs',
#  ' SmartStream Desiginer for InDesign CC2022',
#  ' info brochure hp indigo red invisible ink',
#  ' 3d model of the press',
#  ' what I was searching for',
#  ' Any info would be nice, but nothing is out there',
#  ' Design Print Files For This Ink',
#  ' replacing bridge vacuum belt',
#  ' PDU relay K2',
#  ' konfiguration tool ink level sensor\n',
#  ' second transfer torque',
#  ' Definiciones y ejemplos de como utilizar este ajuste y registrar impresion de segundo pase',
#  ' An email for support.',
#  ' EBM MECHANISM',
#  ' Info on how long inks last before they expire (in the tube)',
#  ' separationscaling',
#  ' HP Indigo 7900 parts catalog',
#  ' How to do a manual BID engage',
#  ' ghosting on 7800',
#  ' user guide',
#  ' Trouble shooting',
#  ' automatic scaling ws6000',
#  ' CA393-09490.  but found nothing. not even other part cataloque for the 7000 press.\nI know it used to be there',
#  ' location',
#  ' https: to open the list of abbreviations',
#  ' MechInit error',
#  ' wiring',
#  ' a PDF similiar to al the other presses',
#  ' HP Indigo 6800 parts catalog',
#  ' a video or pdf showing how to change the blower\n',
#  ' installation manual 25K ',
#  ' User guide for 7600, 7900 Indigo presses',
#  ' how to reconnect press',
#  ' parts cataloque wich used to e on site, ut look like it is dissapeared',
#  ' A DOCUMENT WITH FAULT AND SOLUTION IN IT',
#  ' how to guide',
#  ' como colocar el cabezal al alimentador',
#  ' manual for air pressure calibration',
#  ' a 6k parts catalogue',
#  ' image length unstable',
#  ' substrate compatibility',
#  ' information about the system. but nothing found. ',
#  ' parts catalogue for the 12000',
#  ' double sided printing',
#  ' a list of the rollers in the press that could cause a mark 252mm apart',
#  ' press low water pressure',
#  ' sheet size and and thickness spects',
#  ' This document, as referenced in the \nU9RD0S-VILT_Presentation from my recent training course on Production Pro',
#  ' instructions on how to set up a ticket template to make use of multi-rip partitioning',
#  ' a way to clear the error',
#  ' guide',
#  ' a document telling me to fix the connection to I-serve',
#  ' troubleshooting guide',
#  ' how to replace the main gear lubrication pump',
#  ' Information on how to change the primary contact information associated with our account.',
#  ' something ',
#  ' locate ink flow screw',
#  ' a technical note',
#  ' ITC colent level',
#  ' tutorial',
#  ' Q5379-16610',
#  ' sds sheets for cmyk',
#  ' What it controls',
#  ' setting for 100gsm uncoated stock',
#  ' PIP underlayer replacement',
#  ' press wont calibrate',
#  ' Maximum and Minimum sheet sizes',
#  ' information regards to printing',
#  ' Nestlé Guidance Note on Packaging Inks',
#  ' a list of approved stock',
#  ' Document or video instructions',
#  ' Installer',
#  '   ',
#  ' CA493-06020- HP_DFE_5.2.2_Installation_Guide_IN100',
#  ' CSDB never finished cleaning Database',
#  ' way to install client software onto M1 Mac',
#  ' CA439-02650\nworst search engine ever',
#  ' your search engine is a mess',
#  ' engage',
#  ' a video',
#  ' tutorial',
#  ' solution to fix this warning  on press',
#  ' Indigo Electroink water resistance introduction',
#  ' zahler nicht auf null?\nfehlermeldung geht nicht weg',
#  ' ITM HVPS',
#  ' SmartStream Designer 25 for Illustrator CC2021 Error message: Why will it not install the post-install step?',
#  ' a pdf describing what to look for and possible troubleshooting with metallic (conductive) material',
#  ' yty',
#  ' something that helps',
#  ' Listing of failure codes with HP definitions',
#  ' solución ',
#  ' A user guide on transparent ink relating to the 7x000 series Indigo press',
#  ' documents on scaling for 2ndpass',
#  ' HP6800 / 6600 parts catalogue but nothing!!!!',
#  ' operators manual',
#  ' the 3D footprint of the press as referenced on page 9 of the Site Preparation Guide',
#  ' information on web motion',
#  ' a how to do wizard',
#  ' how to clear the IMO filter lifecycles error',
#  ' video procedura',
#  ' in depth article on the subject',
#  ' troubleshooting itm current failed issues',
#  ' descriptions',
#  ' CA393-08790 is the document',
#  ' parts catalog for all series 3 web presses',
#  ' Solution for Overflow to Waste Error',
#  ' A working link to an online 3D part catalof for a 20000',
#  ' replacement pip drum bearing video',
#  ' Directions to collect print beat coins for our daily usage\n',
#  ' Procedure to verify if skew is present',
#  ' smartstream for indesign cc2021',
#  ' Bid Motor',
#  ' Fade resistant Inks Ink Definitions files for use on press',
#  ' a downloadable pdf for parts not available to order on web ',
#  ' HP SmartStream Designer 16 for InDesign CC2021',
#  ' a report',
#  '  CA494-25020 FR ',
#  ' A video that shows Replacing the Length Adjuster on the Drawer',
#  ' Ink cabinet parts catalog',
#  ' Spot Master info',
#  ' pdf with al the parts and drawings',
#  ' A how to guide and details',
#  ' PDF file',
#  ' dates and locations where training classes for level one and two training are being held if any. ',
#  ' diagram or part number, or why i was getting this error',
#  ' video',
#  ' price breaks per monthly impressions',
#  ' above',
#  ' where i can fine the container',
#  ' How to use it  brochure ',
#  ' Video on finger belt replacement procedure',
#  ' unwinder dancer sensor location',
#  ' where to access',
#  'Angaben zur Lebensmittelunbedenklichkeitserklärung bzw. Informationen zu GMP etc. fehlen mir.\n\nBg\nJens Klingberg ',
#  ' user manual how to build up new ink',
#  ' 20000',
#  ' hp indigo 12000 parts catalog',
#  ' Side Fog TS',
#  ' How much air pressure is needed',
#  ' How much A3 sheets with 100 % coverage, 1 hit will be printed with 1 can of a primer. Thank you',
#  'I did find a title called WH focus- but it opened up to be a blank page. I tried a few different browsers, but nothing worked. ',
#  ' Study material related to Spot master',
#  ' Smartstream 2021',
#  ' What ink is availably for HPI 20000 (fluorescent, invisible ...)',
#  ' Need current part number',
#  ' video',
#  ' draining io oil from the clean side reservoir really fast not sure what cause that',
#  ' UNE VIDEO EXPLIQUATIVE OU DES DOCUMENTS',
#  ' SAFETY DATA SHEET',
#  ' Je cherche donc une fiche technique des encres.',
#  ' parts catalog',
#  ' ILS TS guide for S4',
#  ' Basic Operator Training',
#  ' how to fix that problem',
#  ' tutorial',
#  ' press will not get ready',
#  ' sandwich printing guide',
#  ' 6000 parts catalog',
#  ' troubleshooting guide',
#  ' Max Scaling file to print on press to check the scaling against.',
#  ' Smart Stream Designer for Indesign V16/2021',
#  ' CUAL ES ',
#  ' Documentation detail API capabilities for HP Presses to communicate with external software & devices.',
#  ' 7900 parts catalog',
#  ' unwinder dancer too high error',
#  ' spanish documentation',
#  ' How points are figured',
# ' On-Press Fast Ink Replacement (OFIR) User Guide. I also used search of just OFIR and filtering on 7800',
#  ' parts book 7250',
#  ' how to guide for second pass printing on 6900',
#  ' Site preparation document',
#  ' how to open spm',
#  ' White Ink',
#  ' S4 Inline scanner troubleshooting',
#  ' substrate transport calibrations sheet fed presses',
#  ' NOTHING AVAILBLE',
#  ' it leaks and getting  the correct reading ',
#  'grippers drive home failure',
#  ' Scaling troubleshooting for 7K/10K/12K/100K',
#  ' See above',
#  ' placement of wires when replacing ink tank top',
#  ' Technical note for Error message of: “BSM_FAULT_RMS_TORQUE_LOW\n',
#  ' Ways on how to correct or prevent PLC communication errors ',
#  ' imo filter replacement',
#  ' Digital Matte anything',
#  ' feed head mainenance',
#  ' video instructions on taking out and replacing cap motor for 6600',
#  ' Una descripción de los códigos de los problemas técnicos y orientación para evitar que se repitan',
#  ' description whats the difference between automatic and off mode',
#  ' Guide to add the fonts',
#  ' I am getting an warning when QR codes should be generating. I never use to get it.',
#  ' updated info about the bottom sponge roller ',
#  ' OPE get ready failures repair guide',
#  ' pdf with instructions.',
#  ' scematic for ink cabinet',
#  'When will HP support Esko Color pilot 20?',
#  ' High-resolution, print-ready files for:\n7K\n7eco\n15K\n25K\n6K',
#  ' Part catalogue manual for 6800',
#  'how to market indigo',
#  ' Givatayim/8000 Overview and spec',
#  ' How to guide of heat transfer printing on 7x00',
#  ' A guide with with website information- and step by step instructions to place order.',
#  ' parts catalog that is the same as what is loaded on the presses ',
#  ' On-press Fast Ink Replacement Userguide (CA394-00760)',
#  ' CA493-05630',
#  ' Resource on where to download an ink definition file for POrange021C ink.',
#  ' weblink',
#  ' CU498-03320',
#  ' Second transfer information',
#  ' cleaning station',
#  ' max bzw. durchschnittliche lebens Dauer der IO Filter',
#  ' Security features for labels through QR codes',
#  ' suggestions for solving this problem',
#  " details about running separations ie a CM job that doesn't have YK",
#  ' video',
#  ' movie how to do so  disembly, replace and re-assembly',
#  ' Algún documento que me ayude a interpretar de mejor manera los resultados de OEE',
#  ' CA493-06370 CPR Troubleshooting Doc',
#  ' Parts catalog like on press',
#  ' how to set up files for sliver application',
#  ' Is there such a Wizard?',
#  ' on here easily',
#  ' updated Parts catalog for 7800',
#  ' video',
#  ' a guide that explains how the customer can send his media to HP, be tested and get a certification or not.',
#  ' feeder drawers rails are not good.',
#  ' document',
#  ' How to do....',
#  'Working with HP Indigo ElectroInk Transparent 7900',
#  ' Insulated flow meter',
#  ' z420 recovery process',
#  ' document on pip brake installation',
#  ' the video\n',
#  ' user guide??',
#  ' The PN and item description of IMS',
#  ' Video showing the computer screen of how to change a blanket. ',
#  ' reasons why the substrate sticks to the blanket',
#  ' How to guide',
#  ' Parts catalog 7900 newest version',
#  ' Information in regards to how to lock the ITM cover.',
#  ' plan pieces machine',
#  ' depositing module belts exchange',
#  ' maximum paper size to min and maximum PRINT area to min the 7900 hp is capable of handling.',
#  ' a how to guide',
#  ' No encontre este documento el la zona de conocimientos ,gracias',
#  ' invisible demo file',
#  ' how to use Composer',
#  ' image skew troubleshooting',
#  ' color beat training',
#  ' Video for changing the PIP underlayer ',
#  ' TDS TINTAS\n',
#  ' Perfil necesario que deben cumplir opeadores de prensa Serie 4',
#  ' HOW TO GUIDE for heat transfer printing',
#  ' video or instruction showing how to replace the PIP underlayer on a series 4 12KHD press',
#  ' ink usage guide',
#  ' Any information about what it is; how to find it and how to troubleshoot',
#  ' stacker quality assist',
#  ' How to change Media finger print',
#  ' help with import templates',
#  ' Sincronización de los recursos en todas las prensas de in grupo de dispositivos.',
#  ' i want to know what is CBB mean',
#  ' how to change a flag sensor',
#  " can't preview a job",
#  ' the videos',
#  ' Ho to replace Nalco',
#  ' reason why',
#  ' parts manual',
#  ' separate bid cleaning station manual',
#  ' Automatic Alert Agent 7900 How-To Guide ',
#  ' user instruction for the above problem',
#  ' counter resetting',
#  ' issues related to the bid..for example bid bounce',
#  ' issues related with the bid',
#  ' CA394-10471',
#  ' what to do when the conductivity is to high ,apart of rebuild ink because I rebuild the ink but wont fix the problem ',
#  ' parts catalog 6800',
#  " My 7900 isn't recognizing genuine electroink cans. I cannot find a solution here.",
#  ' how to document',
#  ' how does the bridge actually put together.',
#  ' Material for a Level 4 Operator',
#  ' Diagrams and videos would help level 1 operators that have been on training and need reminding 6 months later...',
#  ' Finger Belt Replacement',
#  ' Anything relevant. I am level 3 SMO, how am I not allowed access to this information?',
#  ' What this error mean',
#  ' unwinder maintenance',
#  ' instructions',
#  ' tutorial on how to change the blanket',
#  ' document explaining how to use this mode of printing',
#  ' TS for skew between frames',
#  ' CA394-10480 Automatic Alert Agent\nfor HP Indigo 7600 Digital Press\nHow-to Guide',
#  ' uso de tintas UV en Indigo 6x00',
#  ' instructions for file creation in terms of embossing, textured clear ink and sandwich printing',
#  ' Check internal and External heating lamps are working.',
#  ' how to guide for installing the Invisible yellow for Series 4 and the ink file',
#  ' something discussing the EVR feature on the 1x000 press',
#  ' relevant documents to the press I was sorting by. Why are sun chemical and michelman inline primer sds sheets even listed here?',
#  ' CA493-00331 Operator Control Station (PP,MR,MR2) Installation.pdf',
#  ' mosaic',
#  ' error OEM_WEB_NOT_READY',
#  ' Instructions',
#  ' User Guide',
#  ' siehe oben\nFehlerbehebung',
#  ' easy release ink how to guide',
#  ' consumable shelf life',
#  ' at least links to: KB0032156 and KB0031375',
#  ' Series 4 Web Press Speed Calculator for Excel. Same like for the Serie 3 Web Press',
#  ' Technical Data Sheet for 12000 inks',
#  ' Baseline document (maintenance procedures) for peak season,\nScope: HP Indigo 7600, 7800, 7900',
#  ' Diagnostico para resolver o problema.',
#  ' Please advise where to install motor board. \n',
#  ' A table similar to the one for the HP6000 or a calculator',
#  '  How to Guide for Heat Transfer application',
#  ' CA393-10920 because its the installation guide, smooth work guys. Tech notes tell me to get a document you dont have and isnt in CE suitcase',
#  ' The steps showing the front dripping fan installation and also the systab changes',
#  ' how to fix it',
#  " It's not available in my software which is the latest available.",
#  ' How i the setup on Indigo for adding zero round without printing color',
#  ' inks\n',
#  ' document where and how to set your user/operator level setting. so this way you can find level 3 documentation ',
#  ' Ws6000 parts catalog',
#  " a document describing the differences between the standard 12000 and a 12000 with TSK. I'm training  customer  (Artifoege net new) next two weeks Level 1 ",
#  ' steps to take when your color calibration fails and why it can fail',
#  ' CA393-07310',
#  ' parts catalog',
#  ' in the files properties, separations section-\nseparation delay- overview',
#  ' A how to guide',
#  ' How to replace a Feeder side blower flat cable ',
#  ' catalogo de peças w7250',
#  ' How many impression should I get from a can of ink',
#  ' Imaging Oil Main Reservoir',
#  ' how to replace and adjust new bearings ws 4500',
#  ' rodillo de enfriamiento del sustrato',
#  ' web ordering video tutorial',
#  'how to clean electrometer on hp press 6600',
#  ' Primer Sensor',
#  ' troubleshooting',
#  ' The steps to do on the hp 12000 or what  i need looking for ',
#  ' What to do if shutting down the Indigo 7900 long term',
#  ' 6900 Installation Manual',
#  ' which would be the most common test with this propierty',
#  ' a guide with description of this matter',
#  ' itc coolant',
#  ' MANUAL ',
#  ' what to use for cleaning the rubber IFR roller',
#  ' A video how to replaced pip foil manually',
#  ' parts catalog',
#  ' how to adjust the voltages on this board',
#  ' Long term shut down procedures',
#  ' any vedeo on how to replace the multipick sensor\n',
#  ' manual de utilização da Ofir',
#  ' how set up CCC for 6800',
#  ' docutation',
#  ' BID cleaning jig video',
#  ' CA394-00760的中文版本',
#  ' Lifespan, Laufleistung der Zuwa Impeller',
#  ' Air pressure calibration wizard',
#  ' Customer L2 documentation',
#  ' Silica filter replacement for 12" filter',
#  ' which nip is the "fr" nip, or a map of  what each of the nips are called, or something useful. ',
#  ' a guide',
#  ' PUW error messages',
#  ' Bestellung für Suction Cups',
#  ' Video',
#  ' video how to replace it',
#  ' HP SmartStream Production Pro Print Server',
#  ' Spot Master',
#  ' substrate list',
#  ' Spot master',
#  ' level 2  and 3 training ',
#  ' Informacion de configuracion y uso del papel ISBC@Rfid en Indigo 7900',
#  ' where to find within service center',
#  ' Parts Catalog',
#  ' temperature sensor',
#  ' material safety data sheets',
#  ' I was looking for information on how to use the Adaptive Image Scaling jig.',
#  ' late color management',
#  ' a trouble shooting guide for this error',
#  ' color up document',
#  ' max print area on a HP7900',
#  ' HP Indigo Print Beat Guideline for commercial presses 4AA5-7533ENW, May 2016, Rev 6 , looking for the L&P version ',
#  ' Part Number: CA494-30930 Rev01_PRINT.pdf\n\nNOTE: Installation von HP Indigo ElectroInk Premium White an HP WS 20.000',
#  ' parts catalog 7900',
#  ' Instructions on how to change an underlayer ',
#  ' a technical document outlining the belts replacement procedure for the feeder horizontal conveyor',
#  ' I expected the new html parts catalog, but there is nothing in Knowledge Zone',
#  ' I expected to find Document for Ceramic Charge Roller ASSY.\nInstallation and Best Practice.',
#  " can't fiond anymore",
#  ' How to switch between manual and automatic first transfer modes on HPI 6900',
#  ' Magnetized Stock',
#  ' Overview of PARS with technical specifications.',
#  ' error Bitmap viewer - Cannot open image java.lang.NullpointerException',
#  ' I serached for How to setup user and undertand user profile/roles in PRintOS',
#  ' how to',
#  ' used to calibrate CDM probe',
#  ' pdf download sheet',
#  ' Parts Catalog for 5500',
#  ' feeder substrate path adjustments for the series 4s',
#  ' a parts catalog for the 5500 press',
#  ' ESTOS LIBROS EN ESPANOL',
#  ' HP Indigo ElectroInk Primer how to guide for the 7x00. I had the following filters: 7900 and English',
#  ' what to do when the ink dont stick',
#  ' information on the 7X00 touch screen monitor.',
#  ' SmartStream Designer for InDesign installation files',
#  ' CA394-08040',
#  ' manual for 7.2.0',
#  ' Speed Table HP 20000',
#  ' LUBT-GREASE SYNTHETIC WITH MINERAL ROHS data sheets',
#  ' Composer 5.0 user reference guide',
#  ' A trouble shooting guide for various issues that are BID associated. (i.e., BID lines, chatter, marks, engage issues, etc)',
#  ' Q5379-16610 - 6900 Footprint.zip',
#  ' how to change imgaing oil filters\n',
#  ' ebm pin ',
#  'How to print Raised effects',
#  'IMO_FILTERS_REPLACE_CLEAN_FLOAT ',
#  "No - I'm looking for Automatic Alert Agent How-To-Guide\n",
#  "Waste bottle full sensor.\nThe press is telling me my waste bottle is full and it's not"
#  ]


# pwp
# user_inputs=['Start up alignment values are incorrect (or very bad)',
#  'Startup calibration alignment screen is empty.',
#  'Streaks appear in the printed content.',
#  'Troubleshooting Guide. Print Quality - Strike-through or mottling',
#  'Supply fan not running',
#  'Gen2.5 Pen Pocket Board. System Status LED Guide',
#  'TOF (Top of Form) faults too early',
#  'TOF sensor improperly positioned',
#  'TOF sensor light beam not working',
#  'TOF was failing to recognize TOF mark during Arch to Arch Calibration',
#  'Temperature Control Problem',
#  'Tensions across the press too low',
#  'Tensions are unstable',
#  'Text Doubling defects occurring in the middle of a print run.',
#  'The crossweb width of the printed content is smaller than expected.',
#  'The downweb length of the printed content is longer or shorter than expected.',
#  'The fonts in the printed content do not match the source file.',
#  'The media width calculated and reported by the Inline Process Controller does not closely match the actual media width.',
#  'Server LED status',
#  'The side 2 content is not aligned with the side 1 content in the downweb direction.',
#  'The size of the chipout region is different than expected.']

#3d
# user_inputs=['Manual graphite blasting - HP Jet Fusion 4200 Series 3D Printing Solutions',
#  'Fusing lamp calibration  - HP Jet Fusion 4200 Series 3D Printing Solutions',
#  'BASF Ultrasint® TPU01 - Process recommendations - HP Jet Fusion 5200 Series 3D Printing Solutions',
#  'Tensile printing recommendations - HP Jet Fusion 4200 3D Printing Solutions',
#  'HP SmartStream 3D Command Center Version 4.1 is available – HP Jet Fusion and Metal Jet 3D Printing Solutions',
#  'Build unit connector repair - HP Jet Fusion 4200 Series 3D Printing Solutions',
#  'New Preventative Maintenance Service Required - HP Jet Fusion 4200 Series 3D Printing Solutions',
#  'Best practices to connect 300L powder supplies - HP Jet Fusion 4200, 5200 Series 3D Printing Solutions',
#  'Gloves not included in the yearly maintenance kit - HP Jet Fusion 4200 Series 3D Printing Solutions',
#  'Removal of pressure sensors in printers -  HP Jet Fusion 4200 Series 3D Printing Solutions',
#  'Part number content changes - HP Jet Fusion 4200 Series 3D Printing Solutions',
#  'Site Preparation Guide additional information - HP Jet Fusion 4200 Series 3D Printing Solutions',
#  'New thermocamera design for PA11 - HP Jet Fusion 5200 Series 3D Printing Solution',
#  'Vane adjustment process - HP Jet Fusion 5200 Series 3D Printing Solutions',
#  'Optimizing job processing times - HP Jet Fusion 5200 Series 3D Printing Solutions',
#  'BASF Ultrasint® TPU01 - Material installation process and fine-tuning - HP Jet Fusion 5200 5600 Series 3D Printing Solutions',
#  'How to calculate the air renovation per hour - HP Jet Fusion 5200 Series 3D Printing Solutions',]


@pytest.mark.asyncio
@pytest.mark.parametrize("user_input", user_inputs)
async def test_faithfulness(user_input):
    """Fetches results for each query and evaluates faithfulness"""
    
    result = await fetch_result(
        search_query=user_input,
        domain='indigo',
        device='',
        persona='engineer',
        size=20,
        source='all', #["alias-kaas-phase2", "alias-docebo-phase2", "alias-knowledge-phase2"], 
        language='en'
    )

    response = result['content']
    print(f"Result ________________{result['citations']}")
    retrieved_contexts = re.findall(r"page_content='(.*?)'(?:,|\))", result["citations"], re.DOTALL)

    text = result['citations']

    documents = re.findall(r'Document\((.*?)\)(?=, Document\(|\]$)', text, re.DOTALL)

    final_results = []

    # 2️⃣ For each document
    for doc_text in documents:
        doc = {}

        # First, extract page_content separately

        # page_content_match = re.search(r"metadata=.*?,\s*page_content='(.*?)'\)", doc_text, re.DOTALL)
        # page_content = page_content_match.group(1) if page_content_match else ''
        page_content_match = re.search(r"page_content\s*=\s*(['\"])(.*?)\1", doc_text, re.DOTALL)
        page_content = page_content_match.group(2) if page_content_match else ''
        # Then extract metadata fields
        doc['documentID'] = re.search(r"'documentID':\s*'([^']*)'", doc_text)
        doc['title'] = re.search(r"'title':\s*'(.*?)'", doc_text)
        doc['description'] = re.search(r"'description':\s*'(.*?)'", doc_text)
        doc['renderLink'] = re.search(r"'renderLink':\s*'(.*?)'", doc_text)
        doc['score'] = re.search(r"'score':\s*([0-9.]+)", doc_text)

        parsed_doc = {
            "documentID": doc['documentID'].group(1) if doc['documentID'] else '',
            "title": doc['title'].group(1) if doc['title'] else '',
            "description": doc['description'].group(1) if doc['description'] else '',
            "renderLink": doc['renderLink'].group(1) if doc['renderLink'] else '',
            "page_content": page_content,
            "score": doc['score'].group(1) if doc['score'] else '',
            "domain": "indigo" 
        }

        final_results.append(parsed_doc)
        
    langchain_llm = LangchainLLMWrapper(llm)
    context_precision = LLMContextPrecisionWithoutReference(llm=langchain_llm)

    faithful = Faithfulness(llm=langchain_llm)

    sample = SingleTurnSample(
        user_input=user_input,
        response=response,
        retrieved_contexts=retrieved_contexts
    )
    context_precision_score = await context_precision.single_turn_ascore(sample)
    faithfulness_score = await faithful.single_turn_ascore(sample)
    # print(f"Test for '{user_input}': Faithfulness Score = {faithfulness_score}")
    retrieved_contexts_str = json.dumps(retrieved_contexts, ensure_ascii=False)
    # retrieved_contexts1=json.dumps(retrieved_contexts1, indent=2)

    # Store results in the database using DbDepends
    with DbDepends() as db:
        ragas_service = RagasEvaluationService(db)
        await ragas_service.log_evaluation(
            session_id = session_id,
            user_input=user_input,
            response=response,
            retrieved_contexts=final_results,
            faithfulness_score=faithfulness_score,
            context_precision_score=context_precision_score,
        )

    assert faithfulness_score > 0.7, f"Faithfulness score too low for input: {user_input}"
    assert context_precision_score > 0.7, f"Context precision score too low ({context_precision_score}) for input: {user_input}"



