resources:
  repositories:
    - repository: templates
      type: githubenterprise
      name: codeway/templates
      endpoint: ghe

trigger:
  branches:
    include:
      - release_to_daily

  paths:
    exclude:
      - Devops/Dev/charts
      - Devops/Dev/codeway-auditlog-release-to-daily-ci.yaml

variables:
  - group: nextjs-knowledgesearch
  - name: branch
    value: release_to_daily

stages:
  - template: templates/codeway-docker-image-v1-beta2.yaml@templates
    parameters:
      anchoreScan: false
      trivyScan: false
      project: knowledge_search
      dockerfile: Dockerfile.audit_log_deletion
      repo: ks_service_auditlog_${{ variables.branch }}
      registryType: harbor
      releaseBranch: ${{ variables.branch }}
      registryParameters:
        - registry: harbor-knowledge_search

  # - template: templates/codeway-helm-library-v0.yaml@templates
  #   parameters:
  #     releaseBranch: ${{ variables.branch }}
  #     chartName: ks-service-batchjob-release-to-daily
  #     chartDir: $(Build.SourcesDirectory)/Devops/Dev/charts/ks-service-batchjob
  #     versionMajorMinor: '5.5'
  #     publishRepositories:
  #       - name: "ks-service-batchjob-release-to-daily"
  #         url: "https://harbor.ext.hp.com/chartrepo/knowledge_search"
  #         username: $(harbor_username)
  #         password: $(harbor_password)
  #         type: harbor      